baseURL: "https://benediktgeissler.de/"
languageCode: de
title: "Benedikt Geißler"
theme: PaperMod
defaultContentLanguage: de

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    simple: true
  twitter:
    enableDNT: true
    simple: true
  vimeo:
    enableDNT: true
  youtube:
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Benedikt Geißler"
  author: "Benedikt Geißler"
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2. January 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true

  #label:
  #  text: "Home"
  #  icon: /apple-touch-icon.png
  #  iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    imageUrl: "/profilbild.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Profilbild
    buttons:
      - name: Beiträge
        url: /posts/
      - name: Tags
        url: /tags/

  socialIcons:
    - name: github
      url: "https://github.com/benediktg"
    - name: twitter
      url: "https://twitter.com/benediktg5"
    - name: mastodon
      url: "https://social.tchncs.de/@benediktg5"
    - name: instagram
      url: "https://www.instagram.com/benediktg5/"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: categories
      name: Kategorien
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
