[build]
  publish = "public/"
  command = "hugo"
  [build.environment]
    HUGO_VERSION = "0.92.1"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  # package = "@netlify/plugin-lighthouse"
  package = "netlify-plugin-hugo-cache-resources"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=31536000"
    Permissions-Policy = "interest-cohort=()"
    #Content-Security-Policy = ""
